### PR TITLE
fill out readme

### PR DESCRIPTION
**Pull request by lauraturk**
I completed my readme.

Would you kindly review it? 

Here's what I added: 
http://g.recordit.co/6vwMJHJv81.gif
http://imgur.com/a/0BKHf

### CODE REVIEW

**Comment by kellymiller6** [comment]
I really enjoy your recordit - it gives me a quick understanding of what your app is and how it works.

**Comment by letakeane** [comment]
Look at that ReadMe! Without seeing the whole thing, I'd also recommend using it as a space to document what you hope to accomplish, big picture, in future iterations :)

**Comment by lauraturk** [comment]
@joshuajhun @tman22 or @rrgayhart

I did not use the template - mil apologies. Have had two people review my readme and offer excellent comments about how I can improve it moving forward.

**Comment by rrgayhart** [comment]
I gave most of my feedback in person - but I would definitely highlight the tech stack that you used - and as you make more UI changes, that Recordit is awesome - keep it updated!

**Pull request merged**
